### ISSUE TITLE
ImportError: dynamic module does not define init function (init_tf2)

### ISSUE THREAD

**Issue by Yukuncn** [koide3/monocular_person_following#17]
When I run robot_controller.py in docker ,I got this error 
Traceback (most recent call last):
  File "/root/catkin_ws/src/monocular_person_following/scripts/robot_controller.py", line 2, in <module>
    import tf
  File "/opt/ros/noetic/lib/python3/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define init function (init_tf2)
could you help me to solve it?Thank you very much!

**Comment by jambalaya666** [comment]
Have you solved it? How did you solve it? I also encountered the following error:
Traceback (most recent call last):
  File '/home/zjt/catkin_ws_mpf/src/monlingual_person_following/scripts/visualization.py', line 6, in <module>
    importtf
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/home/zjt/catkin_ws_mpf/devel/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 34 in <module>
    execute(__fh.read())
  File "<string>", line 38, in <module>
  File "/home/zjt/catkin_ws_mpf/devel/lib/python2.7/dist-packages/tf2_py/__init__.py", line 34 in <module>
    execute(__fh.read())
  File "<string>", line 38, in <module>
ImportError: dynamic module does not define module exported function (PyInit__tf2)
